"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import MoodSelector from "./MoodSelector"; import RadioPlayer from "./RadioPlayer"; import VibeBadge from "./VibeBadge";
import { vibes, type Track, type Vibe } from "@/data/vibes"; import { useYouTubePlayer } from "@/hooks/useYouTubePlayer";

const randomIndex = (length:number, except=-1) => { if(length<=1) return 0; let n=except; while(n===except) n=Math.floor(Math.random()*length); return n };
export default function RadioApp({ initialVibe = vibes[1], initialSelectorOpen = false }: { initialVibe?: Vibe; initialSelectorOpen?: boolean }) { const router=useRouter(); const [started]=useState(true), [selector,setSelector]=useState(initialSelectorOpen), [vibe,setVibe]=useState(initialVibe), [trackIndex,setTrackIndex]=useState(0), [history,setHistory]=useState<number[]>([]), [listeners,setListeners]=useState(28), [fading,setFading]=useState(false), [time,setTime]=useState(""); const track:Track=vibe.tracks[trackIndex];
  const next = useCallback(() => { setTrackIndex(i => { const n=randomIndex(vibe.tracks.length,i); setHistory(h=>[...h.slice(-10),i]); return n }) }, [vibe]);
  const yt=useYouTubePlayer(next);
  useEffect(()=>{ setListeners(18+Math.floor(Math.random()*28)); const tick=()=>setTime(new Intl.DateTimeFormat("de-DE",{hour:"2-digit",minute:"2-digit"}).format(new Date())); tick(); const timer=setInterval(tick,10000); return()=>clearInterval(timer) },[]);
  useEffect(()=>{ if(started) vibe.playlistId ? yt.initPlaylist(vibe.playlistId) : yt.init(track.youtubeId) },[started,vibe.playlistId,track.youtubeId,yt.init,yt.initPlaylist]);
  const previous=()=>{ const last=history.at(-1); if(last===undefined) return next(); setHistory(h=>h.slice(0,-1)); setTrackIndex(last) };
  const selectVibe=(v:Vibe)=>{ setFading(true); setTimeout(()=>{ setVibe(v); setTrackIndex(randomIndex(v.tracks.length)); setHistory([]); setSelector(false); setFading(false); router.push(`/${v.id}`) },300) };
  useEffect(()=>{ const keys=(e:KeyboardEvent)=>{ if(!started||selector||["INPUT","BUTTON"].includes((e.target as HTMLElement).tagName)) return; if(e.code==="Space"){e.preventDefault(); yt.playing?yt.pause():yt.play()} if(e.key.toLowerCase()==="n"||e.key==="ArrowRight") vibe.playlistId?yt.nextVideo():next() }; window.addEventListener("keydown",keys); return()=>window.removeEventListener("keydown",keys) },[started,selector,yt,next,vibe.playlistId]);
  const shownTrack = vibe.playlistId && yt.playlistReady && yt.videoData.video_id ? { youtubeId:yt.videoData.video_id, title:yt.videoData.title||"Deine Playlist", artist:yt.videoData.author||"YouTube", year:new Date().getFullYear() } : track;
  const goNext=()=>vibe.playlistId?yt.nextVideo():next(); const goPrevious=()=>vibe.playlistId?yt.previousVideo():previous(); const shuffle=()=>vibe.playlistId?yt.shufflePlaylist():next();
  return <div className={`relative flex min-h-dvh overflow-hidden bg-ink text-cream ${vibe.seasonal?"is-oktoberfest":""}`}><div className={`bg-scene absolute inset-0 sm:hidden transition-opacity duration-300 ${fading?"opacity-0":"opacity-100"}`} style={{backgroundImage:`url(${vibe.mobileBackground})`}}/><div className={`bg-scene absolute inset-0 hidden sm:block transition-opacity duration-300 ${fading?"opacity-0":"opacity-100"}`} style={{backgroundImage:`url(${vibe.background})`}}/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(8,7,6,.35),rgba(8,7,6,.1)_45%,rgba(8,7,6,.62))]"/><div className="grain absolute inset-0"/><div className={`festive-glow absolute inset-x-0 top-0 h-36 transition-opacity duration-500 ${vibe.seasonal?"opacity-70":"opacity-0"}`} aria-hidden="true"/><div id="youtube-player" className="pointer-events-none absolute -left-[9999px] h-px w-px opacity-0" aria-hidden="true"/><div className="relative z-10 flex min-h-dvh w-full flex-col"><VibeBadge vibe={vibe} onChange={()=>setSelector(true)} listeners={listeners} time={time}/><RadioPlayer track={shownTrack} playing={yt.playing} currentTime={yt.currentTime} duration={yt.duration} onPlayPause={()=>yt.playing?yt.pause():yt.play()} onNext={goNext} onPrevious={goPrevious} onShuffle={shuffle} onSeek={yt.seek}/></div>{selector&&<MoodSelector vibes={vibes} onSelect={selectVibe} onClose={()=>setSelector(false)}/>}</div>
}
